# iOS CMake Toolchain File with vcpkg support
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_VERSION 14.0)
set(CMAKE_OSX_ARCHITECTURES arm64)
set(CMAKE_OSX_DEPLOYMENT_TARGET 14.0)
set(CMAKE_OSX_SYSROOT iphoneos)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fembed-bitcode")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fembed-bitcode")

# iOS-specific compile definitions
add_definitions(-DTARGET_OS_IPHONE=1)
add_definitions(-D__APPLE__=1)

# Disable problematic features on iOS
set(ENABLE_OPENGL OFF CACHE BOOL "" FORCE)
set(ENABLE_VULKAN OFF CACHE BOOL "" FORCE)
set(ENABLE_WXWIDGETS OFF CACHE BOOL "" FORCE)
set(ENABLE_SDL ON CACHE BOOL "" FORCE)
set(ENABLE_BLUEZ OFF CACHE BOOL "" FORCE)
set(ENABLE_DISCORD_RPC OFF CACHE BOOL "" FORCE)
set(ENABLE_HIDAPI OFF CACHE BOOL "" FORCE)
set(ENABLE_CUBEB OFF CACHE BOOL "" FORCE)